Multiple changes.
* Set user as PT story owner when they start it.
* Set `branch` field in RB review request to PT story id.
* Minor refactorings.
* Updated inline comments.

diff --git a/git-flow2-feature-start b/git-flow2-feature-start
--- a/git-flow2-feature-start
+++ b/git-flow2-feature-start
@@ -1,7 +1,13 @@
 #!/bin/bash
 set -e;
+set -o pipefail;
+
+[[ -n ${DEBUG} ]] && set -x
 
 PWD=$1
+
+# The usual prelude
+# =================
 
 . rainbow.sh
 . spinner.sh
@@ -9,33 +15,32 @@ PWD=$1
 
 source_config ${PWD}
 
+# Make sure we're spliting strings by newlines.
+export IFS=$'\n'
+
 trap cleanup EXIT
 
 function cleanup {
   if [[ "$?" -ne "0" ]]; then
     echo
-    echo "Oops, sorry, something went wrong so I'm bailing out."
+    echo "Something was wrong. I'm bailing out. Have a nice day!"
   fi
   stop_spinner 0
 }
 
-# Lowercase and dasherize string.
-function slugify_string {
-  echo -e $1 | awk '{print tolower($0)}' | tr " " "-" | tr "\t" "-"
-}
+# Usual prelude done
+# ==================
 
-if [[ -z ${PROJECT_ID} ]]; then
-  echo "Please specify Pivotal Tracker's PROJECT_ID in '.workflowrc' file"
-  exit 1
-fi
+# Deal with Pivotal Tracker
+# =========================
 
-# Make sure we're spliting strings by newlines.
-export IFS=$'\n'
+ensure_pt_project_id
 
-echogreen "Choosing the Story"
+echogreen "Enter Pivotal Tracker"
 
 start_spinner "Loading stories from Pivotal tracker"
 # Get all relevant stories from PT.
+# TODO: This only gets first 100 stories.
 stories=$(pivotal_tools show stories --number 100  --project-id ${PROJECT_ID}) || {
   # Handle failure.
   echo -e "\n${stories}"
@@ -43,7 +48,10 @@ stories=$(pivotal_tools show stories --number 100  --project-id ${PROJECT_ID}) |
 }
 stop_spinner 0
 
-stories_array=($(echo -e "${stories}" | grep "feature\|bug[\s]+started\|unstarted[^[]+\[" | grep -v "unscheduled[^[]*\["))
+# We're only interested in features and bugs that are started or unstarted.
+stories_array=($(echo -e "${stories}" | \
+  grep "feature\|bug[\s]+started\|unstarted[^[]+\[" | \
+  grep -v "unscheduled[^[]*\["))
 
 echo "I will now list all the suitable stories in Pivotal Tracker I've found."
 
@@ -68,6 +76,10 @@ esac
 # Parse story string to get the story id.
 story_id=`echo ${stories_array[$story_index]} | cut -d' ' -f1 | tr -d \#`
 
+
+# Check if there are any story branches for this story already.
+# =============================================================
+
 [[ -n "${DEBUG}" ]] && echo -e "matching branches:\n `git branch -a | grep ${story_id}`"
 
 matching_branches=$(\
@@ -88,7 +100,10 @@ if [[ -n "${matching_branches}" ]]; then
   exit 0
 fi
 
-echogreen "Creating The Feature Branch"
+# The Git Part
+# ============
+
+echogreen "Enter Git"
 
 flush_stdio
 
@@ -96,9 +111,15 @@ echo "I'll ask you to input a human readable slug now."
 echo "It will be used to create the feature branch."
 read -p "Please insert the slug: " human_name
 
+if [[ -z ${human_name} ]]; then
+  echo "You can't use an empty slug."
+  exit 1
+fi
+
 story_slug=`slugify_string "${human_name}"`
 new_branch="story/${story_slug}/${story_id}"
 
+echo
 echo "This will create a branch called '${new_branch}'"
 read -p "You cool with that? [y/n] " -n 1 -r
 if [[ ! $REPLY =~ ^[Yy]$ ]]; then
@@ -108,23 +129,75 @@ if [[ ! $REPLY =~ ^[Yy]$ ]]; then
   exit 0
 fi
 
+echo; echo
 echo "I will now checkout develop..."
-git checkout develop
+# Let's not bother user by being verbose => `stdout` to `/dev/null`.
+git checkout develop >/dev/null
 
 echo
 
 echo "Creating branch '${new_branch}' now..."
 git checkout -b ${new_branch}
 
-echo
+# The Pivotal Tracker Part
+# ========================
+
+echogreen "Enter Pivotal Tracker"
 
 # Instruct PT backend to update the story.
 start_spinner "Setting story #${story_id} state to 'started'"
 echo
-pivotal_tools start story ${story_id} --project-id ${PROJECT_ID}
+__out=$(pivotal_tools start story ${story_id} --project-id ${PROJECT_ID}) || {
+  echo
+  echo "${__bold}Pivotal Tracker reported an error.${__normal}"
+  print_scream
+  echo "${__bold}${__out}${__normal}"
+  exit 1
+}
 stop_spinner 0
 
-echo; echogreen "Done"
+function rollback_branch {
+  git checkout develop >/dev/null
+  [[ -n "${new_branch}" ]] && git branch -D ${new_branch}
+}
 
-echo "Well done! Story is started and branch is created. And you're on it."
+start_spinner "Setting you as the owner of story ${story_id}..."
+pt_user_id=$(curl -s -X GET -H "X-TrackerToken: ${PIVOTAL_TOKEN}" "https://www.pivotaltracker.com/services/v5/me" 2>/dev/null | \
+  underscore extract id)
+
+if [[ -z "${pt_user_id}" ]]; then
+  print_scream
+  echo "${__bold}Oops... Could not determine your Pivotal Tracker user id.${__normal}"
+  rollback_branch
+  exit 1
+fi
+
+# Set the story owner field to me.
+# PT reports errors in JSON output with HTTP 200 so we have to parse what we get.
+__out=$(curl -X PUT -H "X-TrackerToken: ${PIVOTAL_TOKEN}" \
+  -H "Content-Type: application/json" \
+  -d "{\"owner_ids\": [${pt_user_id}]}" \
+  --silent \
+  "https://www.pivotaltracker.com/services/v5/projects/${PROJECT_ID}/stories/${story_id}") || {
+  echo "Something went wront when trying to access Pivotal Tracker server."
+  exit 1
+}
+stop_spinner 0
+
+# Check if there were errors.
+pt_error=$(echo ${__out} | underscore select ".error" --outfmt text)
+if [[ -n "${pt_error}" ]]; then
+  echo 
+  echo "${__bold}Oops, I could not set the story owner to you.${__normal}"
+  print_scream
+  echo "Please set yourself as the owner of in the web UI using the following link:"
+  echo "https://www.pivotaltracker.com/n/projects/${PROJECT_ID}/stories/${story_id}" 
+  echo
+  echo "original error: ${pt_error}"
+fi
+
+# Aaaaand we're good!
+echo
+echogreen "That's All Folks"
+echo "Nicely done! Story is started and branch is created. And you're on it."
 echo "Have a nice day!"
diff --git a/git-flow2-review-update b/git-flow2-review-update
--- a/git-flow2-review-update
+++ b/git-flow2-review-update
@@ -17,7 +17,7 @@ trap cleanup EXIT
 function cleanup {
   if [[ "$?" -ne "0" ]]; then
     echo
-    echo "I'm bailing out. Have a nice day!"
+    echo "I'm bailing out now. Have a nice day!"
   fi
   stop_spinner 0
 }
@@ -36,10 +36,14 @@ STORY_ID_RX="s|.*\([0-9]\{8,9\}\).*|\1|"
 
 
 function handle_missing_story_id {
-  print_scream
   last_commit_sha=$(git log -1 --pretty=format:"%h")
-  echo "Story id not found in commit message for '${last_commit_sha}'."
+  echo "${__bold}Oh noes, I could not update your review!${__normal}"
+  print_scream
+  echo "${__bold}Story id not found in commit message for '${last_commit_sha}'${__normal}."
+  echo
   echo "Please use 'git commit --amend' to add a 'story-id: <PT story id>' line."
+  echo "That's what I use to figure out what story your commit relates to and I can "
+  echo "find the relevant review to update."
   exit 1
 }
 
@@ -91,13 +95,13 @@ function draw_motivational_dude {
 }
 
 
-draw_motivational_dude
-
 last_commit_log=$(git log -1 --pretty=format:"%s %b")
 line=$(echo -e "${last_commit_log}" | \
   grep -E -i "${STORY_ID_LINE_RX}") || {
   handle_missing_story_id
 }
+
+draw_motivational_dude
 
 story_id=$(echo ${line} | sed "${STORY_ID_RX}")
 github_repo=$(git config --get remote.origin.url | sed -E "s|.*[:/]{1}([^:/]+/[^:]+)$|\1|") 
@@ -149,11 +153,10 @@ flush_stdio
 
 read -p "Please select review to update: " selected_index
 
-if [[ "${selected_index}" -lt "0" ]] || [[ "${selected_index}" -ge "${#review_requests[@]}" ]]; then
-  echo
+check_bounds ${selected_index} ${#review_requests[@]} "0" || {
   echo "Selected index is out of bounds like, totally. Run me again and choose better next time!"
   exit 1;
-fi
+}
 
 case ${selected_index} in
   [0-9]* ) ;;
